"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FormProvider } from "./contexts/FormContext";
import { Header } from "./components/Header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="bg-[#02044a] text-white min-h-screen">
          <div className="m-auto max-w-[980px] min-h-screen flex flex-col">
            <Header />
            <div className="flex-1 flex">
              <div className="w-[250px] border-r-[1px] border-solid border-[#16195c]">
                ...
              </div>
              <div className="flex-1 pl-[40px] pt-[40px]">
                <FormProvider>{children}</FormProvider>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
